name: datamints/datamints-prototype
title: "My super duper Content Block"
#typeName: datamints_prototype
vendorPrefix: tx
group: special
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: TYPO3/Header
    type: Basic
  -
    identifier: template
    label: HTML Template
    type: File
  -
    identifier: tab_text
    type: Tab
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
  -
    identifier: tab_relations
    label: Relations
    type: Tab
  -
    identifier: image
    useExistingField: true
  -
    identifier: files
    label: Files
    type: File
  -
    identifier: records
    type: Collection
    labelField: title
    fields:
      - identifier: title
        type: Text
